#!/bin/bash
# Usage: ./create-router-service-account
#
# Creates a router account in the current project
#
# @source https://docs.openshift.com/container-platform/3.5/install_config/router/default_haproxy_router.html#creating-router-shards

echo “Create router SA in project ‘$(oc project -q)’”
oc create sa router
oc adm policy add-scc-to-user          hostnetwork -z system:serviceaccount:$(oc project -q):router
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:$(oc project -q):router

