- name: OCP | Shutdown Applicaiton Nodes
  hosts: app-nodes
  tasks:
    - name: Stop OpenShift Node
      service:
        name: atomic-openshift-node
        state: stopped

    - include_tasks: tasks/shutdown.yml

- name: OCP | Shutdown Infrastructure Nodes
  hosts: infra-nodes
  tasks:
    - name: Stop OpenShift Node
      service:
        name: atomic-openshift-node
        state: stopped

    - include_tasks: tasks/shutdown.yml

- name: OCP | Shutdown Master Nodes
  hosts: masters
  tasks:
    - name: Stop OpenShift Node
      service:
        name: atomic-openshift-node
        state: stopped

    - name: Stop OpenShift Master API
      service:
        name: atomic-openshift-master-api
        state: stopped

    - name: Stop OpenShift Master Controller
      service:
        name: atomic-openshift-master-controllers
        state: stopped

    - name: Stop ETCD
      service:
        name: etcd
        state: stopped

    - include_tasks: tasks/shutdown.yml
