#- name: Install yum-utils
#  package:
#    name: yum-utils
#    state: present
#
#- name: Detect if reboot is required
#  command: needs-restarting --reboothint
#  register: needs_restart_result
#  failed_when: needs_restart_result.rc > 1
#  changed_when: needs_restart_result.rc == 1

- name: Reboot
  command: "shutdown --reboot +1 'Reboot invoked by Ansible'"
  register: redhat_reboot

- name: Wait for Host After Reboot
  wait_for:
    host: "{{ ansible_hostname }}"
    delay: 65
    port: 22
    state: started
    timeout: 600
  delegate_to: localhost
  become: False
  when: redhat_reboot.changed

