#!/bin/bash


# https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html-single/container-native_storage_for_openshift_container_platform/#chap-Documentation-Red_Hat_Gluster_Storage_Container_Native_with_OpenShift_Platform-Updating_Registry

VOLUME_SIZE=10
GLUSTER_PROJECT=gluster
GLUSTER_ENDPOINTS_NAME=glusterfs-registry-endpoints

echo ''
echo ''
echo 'Switch to gluster project'
oc project ${GLUSTER_PROJECT}
echo '----------'

echo ''
echo ''
echo 'Get Heketi Pod'
export HEKETI_POD=$(oc get pod -n ${GLUSTER_PROJECT} | grep heketi-storage | awk '{print $1}')
echo HEKETI_POD=$HEKETI_POD
echo '----------'

echo ''
echo ''
echo 'Get Heketi Admin Key'
export HEKETI_ADMIN_KEY=$(oc describe pod $HEKETI_POD | grep HEKETI_ADMIN_KEY | awk '{print $2}')
echo HEKETI_ADMIN_KEY=$HEKETI_ADMIN_KEY
echo '----------'

echo ''
echo ''
echo 'Get Registry GID'
export REGISTRY_GID=$(oc get po --selector="docker-registry=default" -o go-template --template='{{printf "%.0f" ((index .items 0).spec.securityContext.fsGroup)}}' -n default)
echo REGISTRY_GID=$REGISTRY_GID
echo '----------'

echo ''
echo ''
echo 'Create named persistent Gluster volume'
oc rsh $HEKETI_POD heketi-cli volume create --size=${VOLUME_SIZE} --name=gluster-registry-volume --gid=${REGISTRY_GID} --user admin --secret $HEKETI_ADMIN_KEY
oc rsh $HEKETI_POD heketi-cli volume list --user admin --secret $HEKETI_ADMIN_KEY
echo '----------'

echo ''
echo ''
echo 'Switch to default project'
oc project default
echo '----------'

echo ''
echo ''
echo 'Create Gluster Registry volume'
echo "apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-registry-volume
  labels:
    glusterfs: registry-volume
spec:
  capacity:
    storage: ${VOLUME_SIZE}Gi
  glusterfs:
    endpoints: ${GLUSTER_ENDPOINTS_NAME}
    path: gluster-registry-volume
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain" | oc create -f - -n default
echo '----------' 
echo ''
echo ''
echo 'Create Gluster Registry claim'
echo "apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-registry-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VOLUME_SIZE}Gi
  selector:
    matchLabels:
      glusterfs: registry-volume" | oc create -f - -n default
echo '----------'

echo ''
echo ''
echo 'Verify Gluster Registry claim'
oc get pvc/gluster-registry-claim -n default
echo '----------'

echo ''
echo ''
echo 'Add the Red Hat Gluster Storage registry to the old registry deployment configuration (dc)'
oc volume dc/docker-registry --add --name=gluster-registry-storage -m /gluster-registry -t pvc --claim-name=gluster-registry-claim -n default
oc rollout status dc docker-registry

# HACK: because even with the wait for the rollout there are still terminating pods and need to wait for them to go
sleep 30
echo '----------'


echo ''
echo ''
echo 'Make the old registry readonly'
echo 'Skipping due to: https://github.com/docker/distribution/issues/1736'
#oc set env dc/docker-registry REGISTRY_STORAGE_MAINTENANCE_READONLY_ENABLED=true
#oc rollout status dc docker-registry
echo '----------'

echo ''
echo ''
echo 'Get one of the registy pods'
oc get po --selector="docker-registry=default"
export REGISTRY_POD=$(oc get po --selector="docker-registry=default" -o go-template --template='{{printf "%s" ((index .items 1).metadata.name)}}')
echo REGISTRY_POD=${REGISTRY_POD}
echo '----------'

echo ''
echo ''
echo 'Rsync /registry to /gluster-registry'
oc rsh ${REGISTRY_POD} rsync -r -v /registry/ /gluster-registry/
echo '----------'

echo ''
echo ''
echo 'Remove the Red Hat Gluster Storage registry form the old dc registry'
oc volume dc/docker-registry --remove --name=gluster-registry-storage
oc rollout status dc docker-registry
echo '----------'

echo ''
echo ''
echo 'Swap the existing registry storage volume for the new Red Hat Gluster Storage volume'
oc volume dc/docker-registry --add --name=registry-storage -t pvc --claim-name=gluster-registry-claim --overwrite
oc rollout status dc docker-registry
echo '----------'

echo ''
echo ''
echo 'Make the registry read write'
echo 'Skipping due to: https://github.com/docker/distribution/issues/1736'
#oc set env dc/docker-registry REGISTRY_STORAGE_MAINTENANCE_READONLY_ENABLED-
#oc rollout status dc docker-registry
echo '----------'
